// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="configuring-maven-repo_{context}"]
= Enable insecure access to a Maven repository

[role="_abstract"]
As an dministrator, you can configure {ProductFullName} to accept self-signed or internal certificates to allow an insecure connection to access your *Maven* repository.

You can clear the Maven cache of your local artifact repository in the *Repositories* view of the {ProductShortName} web console to save disk space.

IMPORTANT: If you set the `rwx_supported` configuration field in the Tackle custom resource (CR) to `false`, {ProductShortName} disables both the *Local artifact repository* field and the *Clear repository* option. Therefore, you cannot clear Maven cache in following procedure. 

.Procedure

. In *Administration* view, click *Repositories* and then click *Maven*.
. Enable the *Consume insecure artifact repositories* switch.
. Optional: To reduce the size of the local *Maven* artifacts, click the *Clear repository* link.
+
NOTE: Depending on the size of the *Maven* repository, the size change might not be evident.