:_newdoc-version: 2.18.5
:_template-generated: 2025-07-31
:_mod-docs-content-type: CONCEPT

[id="roles-personas-users-permissions_{context}"]
= Roles, personas, users, and permissions

[role="_abstract"]
The {ProductFullName} uses three roles, each corresponding to a persona. The roles are predefined in your Red Hat build of Keycloak (RHBK) instance. If you are an {ProductShortName} Administrator, you can create users in your RHBK instance and assign each user one or more roles, one role per persona. 

A user can have more than one role. Each role must correspond to a specific persona:

* The `admin` role corresponds to the administrator persona. Administrators have all the permissions of architects and migrators. They can also create application-wide configuration parameters that other users can consume but cannot change or view, such as Git credentials or Maven `settings.xml` files.

* The `architect` role corresponds to the architect persona. An architect is a technical lead for the migration project. They can run assessments, create and modify applications and related information. They cannot modify or delete sensitive information, but can view it. For example, they can associate an existing set of credentials with a specific application repository.

* The `migrator` role corresponds to the migrator persona. A migrator can analyze applications but cannot create, modify, or delete them. 

* The `project-manager` role corresponds to the project manager persona. Project managers can create, read, update, and delete migration waves. They can also create {mta-dl-full} resources and adoption plans, and update business stakeholders included in a project. They have read-only access to other {ProductShortName} resources. 


{ProductShortName} has two views, *Administration*, and *Migration*. Only an Administrator can access the *Administration* view. Administrators can perform all actions in the *Migration* view. Architects and migrators can see all elements in the *Migration* view but their ability to perform actions in the view depends on their role permissions.