:_newdoc-version: 2.18.3
:_template-generated: 2025-04-10

:_mod-docs-content-type: REFERENCE

[id="persistent-volume-requirements_{context}"]
= Persistent volume requirements

[role="_abstract"]
To successfully deploy the {ProductFullName} Operator, you must create a persistent volume (PV) used by different {ProductShortName} components.

pass:[<!-- vale RedHat.Spelling = NO -->]
The {ProductShortName} Operator requires one `ReadWriteOnce` (RWO) PV for the Hub database. If you set the `rwx_supported` configuration option to `true` in Tackle custom resource (CR), the {ProductShortName} Operator needs two additional `ReadWriteMany` (RWX) PVs used by Maven and the Hub file storage.
pass:[<!-- vale RedHat.Spelling = YES -->]

.Required persistent volumes
[cols="25%,25%,25%,25%", options="header"]
|====
|Name
|Default size
|Access mode
|Description

|`hub database`
|`10Gi`
|RWO
|Hub database

|`hub bucket`
|`100Gi`
|RWX
|Hub file storage required if the `rwx_supported` configuration option is set to `true`.

|`cache`
|`100Gi`
|RWX
|Maven m2 cache required if the `rwx_supported` configuration option is set to `true`.

|`kai-db`
|`5Gi`
|RWO
|{mta-dl-plugin} database required to run an AI-assisted code resolution.
|====
